
openapi: 3.0.2
info:
  title: Todos API
  description: An API for managing todo items
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        "200":
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"

    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Todo"

      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"

components:
  schemas:
    Todo:
      type: object
      description: A todo item
      required:
        - title
        - completed
      properties:
        title:
          type: string
          description: The title of the todo item
        completed:
          type: boolean
          description: The completion status of the todo item
